
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - patch
  - watch
- apiGroups:
  - scheduledscaling.int128.github.io
  resources:
  - scheduledpodscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduledscaling.int128.github.io
  resources:
  - scheduledpodscalers/status
  verbs:
  - get
  - patch
  - update
