# permissions to do viewer scheduledpodscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduledpodscaler-viewer-role
rules:
- apiGroups:
  - scheduledscaling.int128.github.io
  resources:
  - scheduledpodscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduledscaling.int128.github.io
  resources:
  - scheduledpodscalers/status
  verbs:
  - get
