apiVersion: scheduledscaling.int128.github.io/v1
kind: ScheduledPodScaler
metadata:
  name: scheduledpodscaler-sample
spec:
  scaleTarget:
    selectors:
      app: echoserver
  schedule:
    - daily:
        startTime: 20:46:00
        endTime: 20:50:00
      spec:
        replicas: 10
  default:
    replicas: 1
